import { 
  ShoppingCart, Home, Car, Utensils, Coffee, Heart, 
  Plane, Gift, Book, Music, Film, Dumbbell, Zap, Wifi, Phone,
  Briefcase, DollarSign, TrendingUp, Coins, CreditCard, Wallet,
  ShoppingBag, Pizza, Gamepad2, Laptop, Monitor, Smartphone,
  Bike, Bus, Train, Fuel, Package, Shirt, Watch, Glasses,
  Flower2, Sofa, Lamp, Bed, Bath, PawPrint, Stethoscope,
  Pill, Syringe, Thermometer, Baby, GraduationCap, Pencil,
  Palette, Camera, Video, Headphones, Mic, Radio, Tv,
  Newspaper, Mail, MessageCircle, Send, Bell, Star,
  Trophy, Award, Target, Flag, Clock, Calendar,
  MapPin, Globe, Compass, Mountain, Waves, Sun,
  Cloud, Umbrella, Droplets, Snowflake, Wind, Leaf,
  Sparkles, Flame, Scissors, Hammer, Wrench, Settings,
  Shield, Lock, Key, Archive, Folder, FileText,
  BarChart, PieChart, Activity, TrendingDown, CircleDollarSign,
  Banknote, Receipt, Calculator, ShoppingBasket, Store,
  Building, Factory, Warehouse, Users, UserPlus, UserCheck
} from 'lucide-react-native';

export const ICON_OPTIONS = [
  { name: 'ShoppingCart', component: ShoppingCart },
  { name: 'ShoppingBag', component: ShoppingBag },
  { name: 'ShoppingBasket', component: ShoppingBasket },
  { name: 'Store', component: Store },
  { name: 'Package', component: Package },
  { name: 'Home', component: Home },
  { name: 'Building', component: Building },
  { name: 'Factory', component: Factory },
  { name: 'Warehouse', component: Warehouse },
  { name: 'Car', component: Car },
  { name: 'Bike', component: Bike },
  { name: 'Bus', component: Bus },
  { name: 'Train', component: Train },
  { name: 'Plane', component: Plane },
  { name: 'Fuel', component: Fuel },
  { name: 'Utensils', component: Utensils },
  { name: 'Coffee', component: Coffee },
  { name: 'Pizza', component: Pizza },
  { name: 'Heart', component: Heart },
  { name: 'Gift', component: Gift },
  { name: 'Flower2', component: Flower2 },
  { name: 'Book', component: Book },
  { name: 'GraduationCap', component: GraduationCap },
  { name: 'Pencil', component: Pencil },
  { name: 'Music', component: Music },
  { name: 'Film', component: Film },
  { name: 'Video', component: Video },
  { name: 'Camera', component: Camera },
  { name: 'Headphones', component: Headphones },
  { name: 'Mic', component: Mic },
  { name: 'Radio', component: Radio },
  { name: 'Tv', component: Tv },
  { name: 'Gamepad2', component: Gamepad2 },
  { name: 'Dumbbell', component: Dumbbell },
  { name: 'Zap', component: Zap },
  { name: 'Wifi', component: Wifi },
  { name: 'Phone', component: Phone },
  { name: 'Smartphone', component: Smartphone },
  { name: 'Laptop', component: Laptop },
  { name: 'Monitor', component: Monitor },
  { name: 'Briefcase', component: Briefcase },
  { name: 'DollarSign', component: DollarSign },
  { name: 'CircleDollarSign', component: CircleDollarSign },
  { name: 'TrendingUp', component: TrendingUp },
  { name: 'TrendingDown', component: TrendingDown },
  { name: 'Coins', component: Coins },
  { name: 'CreditCard', component: CreditCard },
  { name: 'Wallet', component: Wallet },
  { name: 'Banknote', component: Banknote },
  { name: 'Receipt', component: Receipt },
  { name: 'Calculator', component: Calculator },
  { name: 'Shirt', component: Shirt },
  { name: 'Watch', component: Watch },
  { name: 'Glasses', component: Glasses },
  { name: 'Sofa', component: Sofa },
  { name: 'Lamp', component: Lamp },
  { name: 'Bed', component: Bed },
  { name: 'Bath', component: Bath },
  { name: 'PawPrint', component: PawPrint },
  { name: 'Stethoscope', component: Stethoscope },
  { name: 'Pill', component: Pill },
  { name: 'Syringe', component: Syringe },
  { name: 'Thermometer', component: Thermometer },
  { name: 'Baby', component: Baby },
  { name: 'Palette', component: Palette },
  { name: 'Newspaper', component: Newspaper },
  { name: 'Mail', component: Mail },
  { name: 'MessageCircle', component: MessageCircle },
  { name: 'Send', component: Send },
  { name: 'Bell', component: Bell },
  { name: 'Star', component: Star },
  { name: 'Trophy', component: Trophy },
  { name: 'Award', component: Award },
  { name: 'Target', component: Target },
  { name: 'Flag', component: Flag },
  { name: 'Clock', component: Clock },
  { name: 'Calendar', component: Calendar },
  { name: 'MapPin', component: MapPin },
  { name: 'Globe', component: Globe },
  { name: 'Compass', component: Compass },
  { name: 'Mountain', component: Mountain },
  { name: 'Waves', component: Waves },
  { name: 'Sun', component: Sun },
  { name: 'Cloud', component: Cloud },
  { name: 'Umbrella', component: Umbrella },
  { name: 'Droplets', component: Droplets },
  { name: 'Snowflake', component: Snowflake },
  { name: 'Wind', component: Wind },
  { name: 'Leaf', component: Leaf },
  { name: 'Sparkles', component: Sparkles },
  { name: 'Flame', component: Flame },
  { name: 'Scissors', component: Scissors },
  { name: 'Hammer', component: Hammer },
  { name: 'Wrench', component: Wrench },
  { name: 'Settings', component: Settings },
  { name: 'Shield', component: Shield },
  { name: 'Lock', component: Lock },
  { name: 'Key', component: Key },
  { name: 'Archive', component: Archive },
  { name: 'Folder', component: Folder },
  { name: 'FileText', component: FileText },
  { name: 'BarChart', component: BarChart },
  { name: 'PieChart', component: PieChart },
  { name: 'Activity', component: Activity },
  { name: 'Users', component: Users },
  { name: 'UserPlus', component: UserPlus },
  { name: 'UserCheck', component: UserCheck },
];

export const COLOR_OPTIONS = [
  '#EF4444',
  '#DC2626',
  '#B91C1C',
  '#F59E0B',
  '#D97706',
  '#B45309',
  '#F97316',
  '#EA580C',
  '#C2410C',
  '#FBBF24',
  '#F59E0B',
  '#D97706',
  '#84CC16',
  '#65A30D',
  '#4D7C0F',
  '#22C55E',
  '#16A34A',
  '#15803D',
  '#10B981',
  '#059669',
  '#047857',
  '#14B8A6',
  '#0D9488',
  '#0F766E',
  '#06B6D4',
  '#0891B2',
  '#0E7490',
  '#0EA5E9',
  '#0284C7',
  '#0369A1',
  '#3B82F6',
  '#2563EB',
  '#1D4ED8',
  '#6366F1',
  '#4F46E5',
  '#4338CA',
  '#8B5CF6',
  '#7C3AED',
  '#6D28D9',
  '#A855F7',
  '#9333EA',
  '#7E22CE',
  '#D946EF',
  '#C026D3',
  '#A21CAF',
  '#EC4899',
  '#DB2777',
  '#BE185D',
  '#F43F5E',
  '#E11D48',
  '#BE123C',
  '#64748B',
  '#475569',
  '#334155',
  '#71717A',
  '#52525B',
  '#3F3F46',
];
